### ISSUE TITLE
there is performance potential by implementing move semantics

### ISSUE THREAD

**Issue by odinthenerd** [svenbieg/Clusters#1]
most of the classes in the library are essential handles to heap data, this is low hanging fruit for move based performance gains.

**Comment by svenbieg** [comment]
I think You mean std::move_if_noexcept, but there is a problem because i got uninitialized memory and i am using placement new. Can You help me?

**Comment by svenbieg** [comment]
I've added std::move and some move-contructors.

**Comment by svenbieg** [comment]
Thank You Odin, i now know what noexcept means.

**Comment by svenbieg** [comment]
No noexcept in templates?
