### ISSUE TITLE
single argument constructors should be marked explicit

### ISSUE THREAD

**Issue by odinthenerd** [svenbieg/Clusters#2]
you probably don't want to allow an implicit conversion from unsigned int to an _index_parent_group  https://github.com/svenbieg/Clusters/blob/b46614f0e66491f04f059eb1babcbd7e76b465f8/index.h#L322 

there are a few other less obvious examples

**Comment by svenbieg** [comment]
This constructor is only called once, so the keyword is not necessary.

**Comment by odinthenerd** [comment]
the idea is that it may be inadvertently called because it is not explicit

**Comment by svenbieg** [comment]
Notice that the index-parent-group is not part of the public Interface!
