### ISSUE TITLE
Performance comparisons may be wrong

### ISSUE THREAD

**Issue by jodyhagins** [svenbieg/Clusters#4]
I happened to stumble across your repo, and was a bit curious, so I did a few simple tests.

The comparisons you cite are for inserting in a tight loop, like this...

```c++
Clusters::slist<int, int> slist;
for (int id = 0; id < count; ++id) {
    slist.add(id, 0);
}

std::map<int, int> map;
for (int id = 0; id < count; ++id) {
    map[id] = 0;
}
```

Indeed, for this kind of data, where the input is presented to each collection in sorted order, the cluster is at least twice as fast as the `std::map`.

However, if we change the loop slightly to insert in reverse-sorted-order...

```c++
Clusters::slist<int, int> slist;
for (int id = count; id > 0; --id) {
    slist.add(id, 0);
}

std::map<int, int> map;
for (int id = count; id > 0; --id) {
    map[id] = 0;
}
```

Then the numbers are almost identical, with `std::map` being a bit faster than the cluster.

If you insert in a pseudo-random order (even utilizing a really bad PRNG), inserting into a cluster takes five times as long as the `std::map`.

```c++
srand(seed);
Clusters::slist<int, int> slist;
for (int id = 0; id < count; ++id) {
    slist.add(rand(), 0);
}

srand(seed);
std::map<int, int> map;
for (int id = 0; id < count; ++id) {
    map[rand()] = 0;
}
```

This could be a bug in your implementation, or it could be a bias in your algorithm.  In either case, you may want to take a look because these numbers paint a much different picture than the insert-in-order case.

Running on a mac, built with clang.

**Comment by svenbieg** [comment]
You are right, in reverse order the std::map is faster than the slist. And adding random ids takes about 5 times longer. I could fix this by reducing the group-size to 10.

Reverse order:
![reverse](https://user-images.githubusercontent.com/12587394/73607584-49a3ec00-45b8-11ea-8819-aa923c7811b6.jpg)

Random ids:
![random](https://user-images.githubusercontent.com/12587394/73607588-51639080-45b8-11ea-8bb7-ae07f1c33da2.jpg)

I'm going to reduce the standard-group-size.

Thank You very much for Your investigation.
